spring:
  datasource:
    url: jdbc:mysql://192.168.136.128:3306/evms?useSSL=false&serverTimezone=UTC&characterEncoding=utf8
    username: root
    password: 1
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  jackson:
    serialization:
      INDENT_OUTPUT: true
server:
  port: 8080 